[package]
name = "teleinfo"
version = "1.0.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.clap]
version = "3.0"
features = ["derive"]
