[package]
name = "teleinfo"
version = "1.0.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"

[dependencies]
serde_json = "1.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.clap]
version = "4.0"
features = ["derive"]
